# 딥러닝 구현을 위한 넘파이 복습
* Date: 20.09.23

<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#1.-배열-만들기" data-toc-modified-id="1.-배열-만들기-1">1. 배열 만들기</a></span></li><li><span><a href="#2.-배열-계산" data-toc-modified-id="2.-배열-계산-2">2. 배열 계산</a></span></li><li><span><a href="#3.-행렬-만들기" data-toc-modified-id="3.-행렬-만들기-3">3. 행렬 만들기</a></span></li><li><span><a href="#4.-브로드캐스팅" data-toc-modified-id="4.-브로드캐스팅-4">4. 브로드캐스팅</a></span></li></ul></div>

In [2]:
import numpy as np

## 1. 배열 만들기

In [5]:
x = np.array([1.0, 2.0, 3.0])

In [7]:
print(x)

[1. 2. 3.]


In [9]:
type(x)

numpy.ndarray

In [13]:
print(x, y)

[1. 2. 3.] [2. 4. 6.]


## 2. 배열 계산

In [10]:
y = np.array([2.0, 4.0, 6.0])
x + y

array([3., 6., 9.])

In [11]:
x - y

array([-1., -2., -3.])

In [14]:
x * y

array([ 2.,  8., 18.])

In [12]:
x / y

array([0.5, 0.5, 0.5])

In [15]:
np.dot(x, y)

28.0

In [16]:
x / 2.0

array([0.5, 1. , 1.5])

## 3. 행렬 만들기

In [18]:
A = np.array([[1, 2], [3, 4]])
print(A)

[[1 2]
 [3 4]]


In [19]:
A.shape

(2, 2)

In [20]:
A.dtype

dtype('int32')

## 4. 브로드캐스팅
* 배열이 다를 시, 넘파이 내에서 브로드캐스트 기능을 통해 자동으로 연산이 가능하도록 변환함.

In [27]:
A = np.array([[1, 2], [3, 4]])
B = np.array([10, 20])

In [28]:
A * B

array([[10, 40],
       [30, 80]])

In [23]:
X = np.array([[51, 55], [14, 19], [0, 4]])
print(X)

[[51 55]
 [14 19]
 [ 0  4]]


In [24]:
X[0]

array([51, 55])